import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import {Montserrat} from "next/font/google"
import "./globals.css";
import { Providers } from './providers'

// const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont"
})

export const metadata: Metadata = {
  title: "Dark/Light Mode Toggle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.variable} font-mont bg-light text-dark dark:bg-dark dark:text-light`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
